version: "3.9"

services:
  db:
    image: postgres:16
    container_name: booking-db
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - booking_db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  booking_db_data: